[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
proto = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
