[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
proto = { workspace = true }

reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
