[workspace]
members = ["client", "proto", "server-rust"]

[workspace.dependencies]
proto = { path = "./proto" }

axum = "0.6.12"
prost = "0.11.8"
reqwest = "0.11.15"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tonic = "0.8.3"
tonic-build = "0.8.4"
