[package]
name = "server-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
proto = { workspace = true }

axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
tonic = { workspace = true }
