[package]
name = "server-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
proto = { workspace = true }

actix-web = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
